languages:
   Ruby: true
   JavaScript: false
engines:
  rubocop:
    enabled: true
  csslint:
    enabled: false
ratings:
   paths:
   - app/**
   - lib/**
   - "**.rb"
exclude_paths:
- spec/**/*
- vendor/**/*
